server {
    listen 8080;
    server_name site1.com;
}

server {
    listen 5555;
    server_name site2.com;
    client_max_body_size 10;
    root ./www;
    error_page 404 /errors/404.html;
}